export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FETCH_PRODUCTS_PAGE_START = "FETCH_PRODUCTS_PAGE_START";
export const FETCH_PRODUCTS_PAGE_SUCCESS = "FETCH_PRODUCTS_PAGE_SUCCESS";
export const FETCH_PRODUCTS_PAGE_FAILURE = "FETCH_PRODUCTS_PAGE_FAILURE";

export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILURE = "FETCH_SINGLE_PRODUCT_FAILURE";

export const BACKDROP_TOGGLE = "BACKDROP_TOGGLE";

export const ERROR_RESET = "ERROR_RESET";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCTS_PAGE = "LOAD_PRODUCTS_PAGE";
export const LOAD_SINGLE_PRODUCT = "LOAD_SINGLE_PRODUCT";
