export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FETCH_PRODUCTS_PAGE_START = "FETCH_PRODUCTS_PAGE_START";
export const FETCH_PRODUCTS_PAGE_SUCCESS = "FETCH_PRODUCTS_PAGE_SUCCESS";
export const FETCH_PRODUCTS_PAGE_FAILURE = "FETCH_PRODUCTS_PAGE_FAILURE";

export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILURE = "FETCH_SINGLE_PRODUCT_FAILURE";

export const BACKDROP_TOGGLE = "BACKDROP_TOGGLE";

export const ERROR_RESET = "ERROR_RESET";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCTS_PAGE = "LOAD_PRODUCTS_PAGE";
export const LOAD_SINGLE_PRODUCT = "LOAD_SINGLE_PRODUCT";

export const LOAD_SIGN_UP_FORM = "LOAD_SIGN_UP_FORM";
export const SUBMIT_SIGN_UP_FORM_START = "SUBMIT_SIGN_UP_FORM_START";
export const SUBMIT_SIGN_UP_FORM_SUCCESS = "SUBMIT_SIGN_UP_FORM_SUCCESS";
export const SUBMIT_SIGN_UP_FORM_FAILURE = "SUBMIT_SIGN_UP_FORM_FAILURE";

export const LOAD_LOGIN_FORM = "LOAD_LOGIN_FORM";
export const SUBMIT_LOGIN_FORM_START = "SUBMIT_LOGIN_FORM_START";
export const SUBMIT_LOGIN_FORM_SUCCESS = "SUBMIT_LOGIN_FORM_SUCCESS";
export const SUBMIT_LOGIN_FORM_FAILURE = "SUBMIT_LOGIN_FORM_FAILURE";

export const LOAD_AUTH_ME = "LOAD_AUTH_ME";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REQUEST_UPLOAD_AVATAR = "REQUEST_UPLOAD_AVATAR";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const DELETE_AVATAR = "DELETE_AVATAR";
export const DELETE_AVATAR_SUCCESS = "DELETE_AVATAR_SUCCESS";
