export const ERROR = "ERROR";
export const ERROR_RESET = "ERROR_RESET";

export const FETCH_PRODUCTS_PAGE_START = "FETCH_PRODUCTS_PAGE_START";
export const FETCH_PRODUCTS_PAGE_SUCCESS = "FETCH_PRODUCTS_PAGE_SUCCESS";

export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const SET_CREATED_TO_FALSE = "SET_CREATED_TO_FALSE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const RESET_DELETED_PRODUCT = "RESET_DELETED_PRODUCT";
export const DELETE_FROM_PRODUCTS_STORE = "DELETE_FROM_PRODUCTS_STORE";

export const PATCH_PRODUCT = "PATCH_PRODUCT";
export const PATCH_PRODUCT_START = "PATCH_PRODUCT_START";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";

export const BACKDROP_TOGGLE = "BACKDROP_TOGGLE";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCTS_PAGE = "LOAD_PRODUCTS_PAGE";
export const LOAD_SINGLE_PRODUCT = "LOAD_SINGLE_PRODUCT";

export const LOAD_SIGN_UP_FORM = "LOAD_SIGN_UP_FORM";
export const SUBMIT_SIGN_UP_FORM_START = "SUBMIT_SIGN_UP_FORM_START";
export const SUBMIT_SIGN_UP_FORM_SUCCESS = "SUBMIT_SIGN_UP_FORM_SUCCESS";
export const SUBMIT_SIGN_UP_FORM_FAILURE = "SUBMIT_SIGN_UP_FORM_FAILURE";
export const SET_SUBMIT_SUCCESSED = "SET_SUBMIT_SUCCESSED";

export const LOAD_LOGIN_FORM = "LOAD_LOGIN_FORM";
export const SUBMIT_LOGIN_FORM_START = "SUBMIT_LOGIN_FORM_START";
export const SUBMIT_LOGIN_FORM_SUCCESS = "SUBMIT_LOGIN_FORM_SUCCESS";
export const SUBMIT_LOGIN_FORM_FAILURE = "SUBMIT_LOGIN_FORM_FAILURE";

export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REQUEST_UPLOAD_AVATAR = "REQUEST_UPLOAD_AVATAR";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const DELETE_AVATAR = "DELETE_AVATAR";
export const DELETE_AVATAR_SUCCESS = "DELETE_AVATAR_SUCCESS";
